homeassistant:
  external_url: !secret external_url
  internal_url: !secret internal_url
  packages: !include_dir_named packages
frontend:
  themes: !include_dir_merge_named themes
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
media_source:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.16.0.0/12
    - 127.0.0.1
    - ::1

recorder:
  db_url: !secret ha_db_url
  purge_keep_days: 30
  commit_interval: 60
