services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    restart: unless-stopped

    shm_size: "512mb"

    # If you use docker networks like domum-proxy and iot_vlan50:
    networks:
      - iot_vlan50
      - domum-proxy

    volumes:
      #sudo mkdir -p /etc/domum-core/secrets/frigate
      #sudo nano /etc/domum-core/secrets/frigate/config.yml
      #sudo mkdir -p /mnt/domum/frigate
      - /etc/domum-core/secrets/frigate/config.yml:/config/config.yml
      - /mnt/domum/frigate:/media/frigate
      - /etc/localtime:/etc/localtime:ro

    # Frigate UI and API
    ports:
      - "5001:5000"

    # Optional: USB Coral (uncomment if you have it)
    devices:
      - /dev/bus/usb:/dev/bus/usb

    # Optional: if your system needs extra perms for USB
    privileged: true

    environment:
      - TZ=America/New_York

    labels:
      - traefik.enable=true
      - traefik.docker.network=domum-proxy
      - traefik.http.routers.frigate.rule=Host(`frigate.${DOMUM_DOMAIN}`)
      - traefik.http.routers.frigate.entrypoints=websecure
      - traefik.http.routers.frigate.tls=true
      - traefik.http.routers.frigate.tls.certresolver=cf
      - traefik.http.services.frigate.loadbalancer.server.port=5000

networks:
  domum-proxy:
    external: true
  iot_vlan50:
    external: true
