services:
  go2rtc:
    image: alexxit/go2rtc:latest
    container_name: go2rtc
    restart: unless-stopped
    networks:
      - domum-proxy
      - iot_vlan50
    volumes:
      - /etc/domum-core/secrets/go2rtc:/config
      # ----------------------------
      # Host-side quick setup steps:
      # ----------------------------
      # 1) Create the config directory on the host:
      #    sudo mkdir -p /etc/domum-core/secrets/go2rtc
      #
      # 2) Create a config file:
      #    sudo nano /etc/domum-core/secrets/go2rtc/go2rtc.yaml
    labels:
      - traefik.enable=true
      - traefik.docker.network=domum-proxy
      - traefik.http.routers.go2rtc.rule=Host(`go2rtc.${DOMUM_DOMAIN}`)
      - traefik.http.routers.go2rtc.entrypoints=websecure
      - traefik.http.routers.go2rtc.tls=true
      - traefik.http.routers.go2rtc.tls.certresolver=cf
    enviroment:
      -TZ=America/New_York
networks:
  domum-proxy:
    external: true
  iot_vlan50:
    external: true

