services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    restart: unless-stopped
    networks:
      - domum-internal
    environment:
      - TZ=America/New_York
    volumes:
      - /opt/domum-core/compose/automation/mosquitto:/mosquitto/config
      - /opt/domum-core/compose/automation/mosquitto/data:/mosquitto/data
      - /opt/domum-core/compose/automation/mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
    profiles:
      - core

networks:
  domum-internal:
    external: true
