services:
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: unless-stopped
    networks:
      - domum-internal
      - domum-proxy
    volumes:
      - ${DOMUM_DIR:-/opt/domum-core}/data/nodered:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.nodered.rule=Host(`nodered.${DOMUM_DOMAIN}`)
      - traefik.http.routers.nodered.entrypoints=websecure
      - traefik.http.routers.nodered.tls=true
      - traefik.http.routers.nodered.tls.certresolver=cf
      - traefik.http.services.nodered.loadbalancer.server.port=1880
      - traefik.http.routers.nodered.middlewares=securityHeaders@file
    profiles:
      - night
