services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    restart: unless-stopped
    networks:
      - domum-internal
      - domum-proxy
    environment:
      - TZ=America/New_York
    volumes:
      - /opt/domum-core/compose/automation/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_1069b4aa32a6ed118a20e8a32981d5c7-if00-port0:/dev/serial/by-id/sonoff-zigbee
    labels:
      - traefik.enable=true
      - traefik.docker.network=domum-proxy
      - traefik.http.routers.z2m.rule=Host(`z2m.${DOMUM_DOMAIN}`)
      - traefik.http.routers.z2m.entrypoints=websecure
      - traefik.http.routers.z2m.tls=true
      - traefik.http.routers.z2m.tls.certresolver=cf
      - traefik.http.routers.z2m.middlewares=securityHeaders@file,forwardedHeaders@file
      - traefik.http.services.z2m.loadbalancer.server.port=8080
    profiles:
      - core

networks:
  domum-internal:
    external: true
  domum-proxy:
    external: true
