http:
  routers:
    cockpit:
      rule: "Host(`cockpit.ladomum.com`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cf
      service: cockpit-svc
      middlewares:
        - forwardedHeaders@file

  services:
    cockpit-svc:
      loadBalancer:
        passHostHeader: true
        serversTransport: cockpit-transport
        servers:
          - url: "https://10.0.10.2:9090"

  serversTransports:
    cockpit-transport:
      insecureSkipVerify: true
