http:
  routers:
    cockpit:
      rule: "Host(`cockpit.ladomum.com`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cf
      service: cockpit-svc
      middlewares:
        - securityHeaders@file

  services:
    cockpit-svc:
      loadBalancer:
        serversTransport: cockpit-transport
        servers:
          - url: "https://127.0.0.1:9090"

  serversTransports:
    cockpit-transport:
      insecureSkipVerify: true
