http:
  middlewares:
    securityHeaders:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "no-referrer"
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true

    forwardedHeaders:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Port: "443"

    # Not always required for HA, but harmless and helps some setups
    websocketHeaders:
      headers:
        customRequestHeaders:
          Connection: "Upgrade"
          Upgrade: "websocket"
