services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    networks:
      - domum-proxy
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
    - traefik.enable=true
    - traefik.http.routers.portainer.rule=Host(`portainer.${DOMUM_DOMAIN}`)
    - traefik.http.routers.portainer.entrypoints=websecure
    - traefik.http.routers.portainer.tls=true
    - traefik.http.routers.portainer.tls.certresolver=cf
    - traefik.http.services.portainer.loadbalancer.server.port=9000
    profiles:
      - core

networks:
  domum-proxy:
    external: true
